# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: 'Blog Template'
email: hello[at]ramottamado[dot]dev
enc_email: '&#104;&#101;&#108;&#108;&#111;&#64;&#114;&#97;&#109;&#111;&#116;&#116;&#97;&#109;&#97;&#100;&#111;&#46;&#100;&#101;&#118;'
author: 'Tamado Ramot Sitohang'
description: > # this means to ignore newlines until "baseurl:"
  Blog template.<br />
  Made with ❤️.
baseurl: "/" # the subpath of your site, e.g. /blog
url: "https://template.ramottamado.dev" # the base hostname & protocol for your site
logo: '/favicon.png'
fb_app_id: 2815620495116640
fb_pages: 103250301049786
fb_author: 100000091609630
gravatar_author: "https://www.gravatar.com/avatar/90b290098c6a408c075ab0fd3b1f5783?s=300"
linkedin_username: ramottamado
github_username: ramottamado
twitter_username: theramottamado
ig_username: theramottamado
fb_username: theramottamado
permalink: /:title/
excerpt_separator: <!--more-->
sitemap:
  changefreq: monthly

# Build settings
markdown: kramdown
kramdown:
  syntax_highlighter_opts:
    default_lang: html
